### ISSUE TITLE
Github page missing details of 0.2 release

### ISSUE THREAD

**Issue by toddjonker** [itemis/xtext-testing#4]
The update site on bintray includes a `0.2` release, but there's no mention of it under the releases at https://github.com/itemis/xtext-testing/releases

It would be helpful if the metadata on github were updated to describe the new release, so customers can understand what's changed since 0.1.

Thanks!

**Comment by kthoms** [comment]
There were no relevant changes except for setting up the release process (build & deploy of the composite release repository) and a bug fix.
I don't want to make the effort yet to set up release notes.

**Comment by franzbecker** [comment]
I don't think you would have to set up release notes but a tag on the source code would be good to have. How was the release deployed if there is no tag anyway? Manually?
